namespace VsixGallery
{
	/// <summary>
	/// Persisted alongside an extension's <c>extension.json</c> in a hidden
	/// sidecar file (<c>.manage.json</c>). Holds the SHA-256 hash (Base64)
	/// of the manage token chosen by the publisher (or auto-generated by
	/// the server) at upload time. The plaintext token is never stored.
	/// </summary>
	public class ManageInfo
	{
		public string? TokenHash { get; set; }
	}

	/// <summary>
	/// A package that has been soft-deleted into the trash, paired with the
	/// timestamp it was moved there.
	/// </summary>
	public record TrashedPackage(Package Package, System.DateTime? DeletedAt);
}
